<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Web Crawler</title>
    
    <style>
        body {
            font-family: sans-serif;
        }

        a, a:visited {
            color: #6495ed;
            text-decoration: none;
        }
	    a:hover {
          text-decoration: underline;
        }

	    a.subdomain-link::after {
            content: '(subdomain)';
            font-size: 5px;
            color: #000;
            margin-left: 8px;
        }

        .header {
            padding: 10px 20px;
        }

        .header h1 {
            font-size: 24px;
        }

        .content {
            display: flex;
            flex-direction: row-reverse;
        }

        .table,
        .table th,
        .table td {
            flex: 1;
            font-size: 16px;
            border: 1px solid #777;
        }
        .table {
            border-collapse: collapse;
        }
        .table th {
            padding: 10px 6px;
        }
        .table td {
            padding: 10px;
        }
        .table thead {
            background: #eee;
        }

        .total-results-wrapper {
            display: flex;
            flex-direction: column;
            /* justify-content: center; */
            padding: 0 20px;
        }

        .total-results {
            border: 1px solid #eee;
            border-radius: 10px;
            background-color: #eee;
            display: inline-block;
            padding: 12px;
        }

        .status-code--good {
            font-weight: bold;
            color: green;
        }

        .status-code--redirect {
            font-weight: bold;
            color: gold;
        }

        .status-code--bad {
            font-weight: bold;
            color: red;
        }

        @media only screen and (max-width: 1200px) {
            .content {
                flex-direction: column-reverse;
            }

            .table {
                margin: 0 20px;
            }

            .total-results-wrapper {
                padding: 20px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <?php echo $this->getContent(); ?>
    </div>
</body>
</html>